server:
  port: 9000

security:
  jwt:
    key-store: classpath:keystore200619.jks
    key-store-password: abc123
    key-pair-alias: oauth2_200619
    key-pair-password: abc123

spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true